### PR TITLE
Spanish Language Support

### PR DESCRIPTION
**Pull request by SClarkWT**

### CODE REVIEW

**Comment by dcpurton** [comment]
Also, there is an existing `.gitignore` file that already includes *.log. You don't seem to have this file in your repository.

**Comment by SClarkWT** [comment]
@dcpurton are you meaning in your main repository? Could you drop me the code? I'm not seeing it.

**Comment by dcpurton** [comment]
Oh... That would be because I didn't actually have `.gitignore` committed! Sorry! It's there now and includes *.log as well as a range of other intermediate files.

**Comment by dcpurton** [comment]
Looks good. I'll merge it.

**Comment by baem2** [comment]
I agree in that \uspunctuation case: Usually I'm using "Title", only in one article I now need the US punctuation. So I am happy to use a little trick this time, but have the normal punctuation in my other files.

**Pull request merged**
